---
title: "World Politics"
description: "POLSC 145 Spring 2022 course page"
site: distill::distill_website
---

Welcome, this page will serve as the homepage for POLSC 343 US foreign policy (Fall 2021).


## Course Summary
 
This course is designed to give undergraduate students an introduction to the topics and methods associated
with the study of world politics. As one of the three main subfields in political science, international
relations evolved as the study of nation-states and their interactions in the global sphere. Over the past
several centuries the type and frequency of these interactions, along with the range of actors involved, have
increased exponentially. Given that global political and economic events are increasingly relevant for individuals
around the world, it is imperative that we develop a solid foundation for understanding the actors,
incentives, and processes that drive these events. Accordingly, this course will focus on basic facts and key
concepts related to the study of international relations. We will also focus on how to analyze the casual
processes underpinning events of interest.

## Course Objectives

1. The overarching goal is to develop an understanding
of the systematic forces that shape US foreign policymaking. Please note that this is different than
prescribing what policy *should* be (though this is also an important consideration when considering our motivations for studying the topic and reading course materials.
2. Identify the key actors that influence foreign policy.
3. Understand how and when the influence of actors varies (e.g. across time, issue area, etc.).
4. Identify the key issues confronting policymakers and society. 
5. Identify general trends in US foreign policy over time. 
    - What's changed? 
    - What stays the same?
    - When and why do we see changes in behavior or policies?
6. Students should develop a familiarity with social science research processes, practices. Specifically, students should have:
    - A basic understanding of how to read social scientific research articles. 
    - A basic understanding of research design considerations
    - A basic understanding of what the scope and limitations of research articles


