---
title: "World Politics"
subtitle: "International Finance"
author: "Michael E. Flynn"
institute: "Kansas State University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "lecture_theme.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
      titleSlideClass: [middle, left, inverse]
---
  
```{r setup, include = FALSE, echo=FALSE, warning=FALSE}
#remotes::install_github("gadenbuie/xaringanExtra")

library(ggplot2)
library(data.table)
library(peacesciencer)
library(kableExtra)
library(tidyverse)
library(janitor)
library(here)
library(ghibli)
library(ggforce)
library(scales)
library(rmapshaper)
library(sf)
library(sp)
library(tmap)
library(raster)
library(broom)
library(xaringanExtra)
library(gghighlight)
library(tidyquant)

xaringanExtra::use_scribble()
xaringanExtra::use_editable(expires = 365)

knitr::opts_chunk$set(comment = '', dpi = 400, fig.width = 8, fig.height = 5, warning = FALSE, echo = FALSE, message = FALSE)

sysfonts::font_add_google("Oswald", family = "oswald")
showtext::showtext_auto()

# Windows and Mac seem to process the fotn differently
if (Sys.info()[[1]] == "Windows"){
  
  basesize <- 35
  
} else {
  
  basesize <-  11
  
}

update_geom_defaults("text", list(size = 10, family = "oswald", fontface = "plain", lineheight = 0.2))


# Regular plot theme
theme_flynn <- function(){ 
  
  theme_linedraw(base_size = basesize, base_family = "oswald") %+replace% 
    
    theme(plot.title = element_text(face = "bold", size = basesize * 1.3, hjust = 0, margin = margin(t = 0, b = 0.2, l = 0, r = 0, unit = "cm")),
          plot.subtitle = element_text(size = basesize, hjust = 0, margin = margin(t = 0.0, b = 0.2, unit = "cm")),
          plot.caption = element_text(face = "italic", size = basesize * 0.6, hjust = 1, lineheight = 0.3, margin = margin(t = 0.2, unit = "cm")),
          panel.border = element_rect(fill = NA, size = 0.2),
          strip.background = element_rect(fill = "gray80", color = "black", size = 0.2),
          strip.text = element_text(size = basesize, color = "black", face = "bold", margin = margin(t = 0.2, b = 0.2, l = 0.2, r = 0.2, unit = "cm")),
          panel.background = element_rect(size = 0.2),
          panel.grid.major = element_line(color = "gray70", size = 0.15),
          panel.grid.minor = element_line(color = "gray90", size = 0.1),
          axis.title = element_text(face = "bold", size = basesize),
          axis.title.y = element_text(angle = 90, margin = margin(t = 0, r = 0.2, b = 0, l = 0, unit = "cm")),
          axis.title.x = element_text(margin = margin(t = 0.2, r = 0, b = 0, l = 0, unit = "cm")),
          axis.ticks = element_line(size = 0.1),
          axis.ticks.length = unit(0.1, "cm"),
          legend.title = element_text(size = basesize, face = "bold", hjust = 0, margin = margin(t = 0, b = -0.3, l = 0, r = 0, unit = "cm")),
          legend.text = element_text(size = basesize, hjust = 0, margin = margin(t = 0, b = 0, l = -0.5, r = 0, unit = "cm")),
          legend.box.spacing =  unit(0.2, "cm"),
          plot.margin = margin(0.3, 0.3, 0.3, 0.3, unit = "cm"))
}

#install.packages("RefManageR")

#library(RefManageR)
#library(bibtex)
#BibOptions(check.entries = FALSE,
#           bib.style = "authoryear", # Bibliography style
#           max.names = 3, # Max author names displayed in bibliography
#           sorting = "nyt", #Name, year, title sorting
#           cite.style = "authoryear", # citation style
#           style = "markdown",
#           hyperlink = FALSE,
#           dashed = FALSE)

#myBib <- ReadBib(here::here("../../classrefs.bib", check = FALSE))

```

# Lecture Overview

1. What is international finance?

2. Why do people invest abroad?

3. Controversy and conflict in international finance



---
# Key Questions and Goals

1. How does the Heckscher–Ohlin Theory help us to understand capital flows?

2. What sorts of political factors affect lending and borrowing decisions?

3. How do international financial flows relate to trade? To monetary policy?



---
class: center, middle, inverse

# What is international finance?

Factors of production

- Land

- Unskilled labor

- Skilled labor (human capital)

- Capital



---
# What is international finance?

Finance

- Investment and the allocation of capital

- About the flow of money across borders

Monetary policy

- Concerns the valuation, supply, and manipulation of currency



---
# What is international finance?

Three main types of financial relations:

- Portfolio investment

- Sovereign lending

- Foreign direct investment (FDI)



---
# What is international finance?

Portfolio investment

- Buying stock (equity) in a foreign company

- Lending money to a foreign company or government (buying bonds)

- No control over investment (usually)




---
# What is international finance?

Sovereign lending

- Loans from private financial institutions to foreign governments (buying bonds)

- This is the biggest category of portfolio investment (a subset of portfolio investment)

- Debt



---
# What is international finance?

Foreign Direct Investment (FDI)

- Investment by a company in one country into a foreign country

- Buying or investing in a subsidiary, opening a factory or branch

- Control over investment




---
# What is international finance?

Defining debt relationships:

- Creditors: People who loan money

- Debtors: People who borrow money




---
class: center, middle, inverse

# Why invest overseas?





---
# Why invest overseas?

Profit: To make (more) money

Heckscher–Ohlin theory

- Countries will export goods that make intensive use of the factors that are abundant

- Countries will import goods that make intensive use of the factors that are scarce




---
# Why invest overseas?

Holders of capital make money by investing it with the expectation of generating a return

Returns can take the form of:

- Access to cheap labor or foreign markets may also increase returns to investment

- Dividends, interest, appreciation, etc.